version: '3.8'

services:
  client:
    build:
      context: ./nuxt_client  # 指向 Dockerfile 所在目录
    image: nuxt_client:latest
    container_name: client
    hostname: client-host  # 设置容器的主机名
    ports:
      - "3001:3001"  # 将容器内部的 3001 端口映射到主机的 3001 端口
    networks:
      - app-network  # 使用自定义网络 app-network

  service:
    build:
      context: ./nuxt_service
    image: nuxt_service:latest
    container_name: service
    hostname: service-host  # 设置容器的主机名
    ports:
      - "3000:3000"  # 将容器内部的 3001 端口映射到主机的 3001 端口
    networks:
      - app-network  # 使用自定义网络 app-network

  mysql:
    build:
      context: ./nuxt_mysql
    image: nuxt_mysql:latest
    container_name: mysql
    hostname: mysql-host  # 设置容器的主机名
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nuxt_data
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    networks:
      - app-network  # 使用自定义网络 app-network

networks:
  app-network:
    driver: bridge  # 使用 bridge 驱动来创建一个自定义网络
